//! Workspace tooling. `cargo run -p xtask -- gen-header` emits the libwaddle
//! C header to target/include/waddle.h (a CI artifact, never checked in).

use std::path::PathBuf;

fn main() {
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("gen-header") => gen_header(),
        other => {
            eprintln!("xtask: unknown subcommand {other:?}; available: gen-header");
            std::process::exit(2);
        }
    }
}

fn gen_header() {
    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives in the workspace")
        .to_path_buf();
    let crate_dir = workspace.join("crates/waddle-ffi");
    let out_dir = workspace.join("target/include");
    std::fs::create_dir_all(&out_dir).expect("create target/include");
    let out_path = out_dir.join("waddle.h");

    #[allow(clippy::field_reassign_with_default)] // Config is large; field-by-field is clearer
    let config = {
        let mut config = cbindgen::Config::default();
        config.language = cbindgen::Language::C;
        config.include_guard = Some("WADDLE_H".into());
        config.header = Some(
            "/* libwaddle — the Waddle C ABI.\n\
         * ABI STABILITY: UNSTABLE (amendment N5): this surface is unstable until\n\
         * both the Python SDK and waddle_ros consume it in anger. Generated by\n\
         * `cargo run -p xtask -- gen-header`; never edit by hand. Apache-2.0. */\n\
         #define WADDLE_ABI_UNSTABLE 1"
                .into(),
        );
        config.cpp_compat = true;
        config.documentation = true;
        config
    };

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("cbindgen generation failed")
        .write_to_file(&out_path);
    println!("wrote {}", out_path.display());
}
